greet=['Hello','Hi',
       'Hi','Hello',
       'Greetings!','Hello',
       'Hello','Greetings!',
       'How are you?','I am Good.  How about you?',
       'I am fine thank you',"You're welcome",
       'I am fine','ok :-)',
       'How are you doing?','Very well, thanks.',
       'Nice to meet you.','Thank you.',
       'nice to meet you.','Thank you.',
       'It is a pleasure to meet you.','Thank you. You too.',
       "what's up?",'Not much.',
       "What's up?",'Not too much.',
       "so what's up?",'Nothing much.',
]